# Generated by Django 4.2.2 on 2023-07-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codingData', '0003_userdetails_createdon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='totalQuestions_codechef',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='totalQuestions_codeforces',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='totalQuestions_gfg',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='totalQuestions_hackkerank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='totalQuestions_leetcode',
            field=models.IntegerField(default=0),
        ),
    ]
